name: Deploy

env:
  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

on:
    push:
      branches: [main]
    pull_request:
      branches:
        - main
        
jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          npm install
          npm run test-component

      - name: Deploy
        # Only run this step if the branch is main
       
        run: curl "$deploy_url"
        